name: Survival
version: 1.1.2
description: WorldSMP survival plugin.
author: Spacey
main: com.theworldsmp.survival.Survival
api-version: 1.14
commands:
  message:
    aliases: [msg, pm, whisper, tell]
    description: Private message a player
  reply:
    aliases: [r]
    description: Private message the last player